In [20]:
# Import required libraries
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', None)

pd.set_option('display.width', None)

In [2]:
df = pd.read_csv("IPL.csv")

/tmp/ipykernel_3293/4237585619.py:1: DtypeWarning: Columns (20,32,43,46,47,48,51,64) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("IPL.csv")

In [21]:
# Display the first five rows
df.head()

,match_id,date,match_type,event_name,innings,batting_team,bowling_team,over,ball,ball_no,batter,bat_pos,runs_batter,balls_faced,bowler,valid_ball,runs_extras,runs_total,runs_bowler,runs_not_boundary,extra_type,non_striker,non_striker_pos,wicket_kind,player_out,fielders,runs_target,umpires_call,player_of_match,match_won_by,win_outcome,toss_winner,toss_decision,venue,city,day,month,year,season,gender,team_type,superover_winner,result_type,method,balls_per_over,overs,event_match_no,stage,match_number,team_runs,team_balls,team_wicket,new_batter,batter_runs,batter_balls,bowler_wicket,batting_partners,next_batter,striker_out,ball_result
0,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,0,SC Ganguly,1,0.0,1.0,P Kumar,1.0,1.0,1.0,0.0,False,legbyes,BB McCullum,2.0,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6.0,20.0,1,Unknown,Unknown,1.0,1.0,0.0,NaN,0.0,1.0,0.0,"('BB McCullum', 'SC Ganguly')",NaN,False,Dot Ball
1,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,0,BB McCullum,2,0.0,1.0,P Kumar,1.0,0.0,0.0,0.0,False,NaN,SC Ganguly,1.0,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6.0,20.0,1,Unknown,Unknown,1.0,2.0,0.0,NaN,0.0,1.0,0.0,"('BB McCullum', 'SC Ganguly')",NaN,False,Dot Ball
2,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0,BB McCullum,2,0.0,0.0,P Kumar,0.0,1.0,1.0,1.0,False,wides,SC Ganguly,1.0,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6.0,20.0,1,Unknown,Unknown,2.0,2.0,0.0,NaN,0.0,1.0,0.0,"('BB McCullum', 'SC Ganguly')",NaN,False,Dot Ball
3,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,0,BB McCullum,2,0.0,1.0,P Kumar,1.0,0.0,0.0,0.0,False,NaN,SC Ganguly,1.0,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6.0,20.0,1,Unknown,Unknown,2.0,3.0,0.0,NaN,0.0,2.0,0.0,"('BB McCullum', 'SC Ganguly')",NaN,False,Dot Ball
4,335982,2008-04-18,T20,Indian Premier League,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,0,BB McCullum,2,0.0,1.0,P Kumar,1.0,0.0,0.0,0.0,False,NaN,SC Ganguly,1.0,NaN,NaN,NaN,NaN,False,BB McCullum,Kolkata Knight Riders,140 runs,Royal Challengers Bangalore,field,M Chinnaswamy Stadium,Bangalore,18,4,2008,2007/08,male,club,NaN,NaN,NaN,6.0,20.0,1,Unknown,Unknown,2.0,4.0,0.0,NaN,0.0,3.0,0.0,"('BB McCullum', 'SC Ganguly')",NaN,False,Dot Ball

In [22]:
# Display the number of rows and columns
print("Dataset Shape:", df.shape)

Dataset Shape: (82505, 60)

In [23]:
# Display the number of rows and columns
print(df.columns)

Index(['match_id', 'date', 'match_type', 'event_name', 'innings',
       'batting_team', 'bowling_team', 'over', 'ball', 'ball_no', 'batter',
       'bat_pos', 'runs_batter', 'balls_faced', 'bowler', 'valid_ball',
       'runs_extras', 'runs_total', 'runs_bowler', 'runs_not_boundary',
       'extra_type', 'non_striker', 'non_striker_pos', 'wicket_kind',
       'player_out', 'fielders', 'runs_target', 'umpires_call',
       'player_of_match', 'match_won_by', 'win_outcome', 'toss_winner',
       'toss_decision', 'venue', 'city', 'day', 'month', 'year', 'season',
       'gender', 'team_type', 'superover_winner', 'result_type', 'method',
       'balls_per_over', 'overs', 'event_match_no', 'stage', 'match_number',
       'team_runs', 'team_balls', 'team_wicket', 'new_batter', 'batter_runs',
       'batter_balls', 'bowler_wicket', 'batting_partners', 'next_batter',
       'striker_out', 'ball_result'],
      dtype='object')

In [25]:
# Display dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82505 entries, 0 to 82504
Data columns (total 60 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   match_id           82505 non-null  int64
 1   date               82504 non-null  datetime64[ns]
 2   match_type         82504 non-null  object
 3   event_name         82504 non-null  object
 4   innings            82505 non-null  int64
 5   batting_team       82504 non-null  object
 6   bowling_team       82504 non-null  object
 7   over               82505 non-null  int64
 8   ball               82505 non-null  int64
 9   ball_no            82505 non-null  int64
 10  batter             82504 non-null  object
 11  bat_pos            82505 non-null  int64
 12  runs_batter        82504 non-null  float64
 13  balls_faced        82504 non-null  float64
 14  bowler             82504 non-null  object
 15  valid_ball         82504 non-null  float64
 16  runs_extras        82504 non-null  float64
 17  runs_total         82504 non-null  float64
 18  runs_bowler        82504 non-null  float64
 19  runs_not_boundary  82504 non-null  object
 20  extra_type         4663 non-null   object
 21  non_striker        82504 non-null  object
 22  non_striker_pos    82504 non-null  float64
 23  wicket_kind        4120 non-null   object
 24  player_out         4120 non-null   object
 25  fielders           2968 non-null   object
 26  runs_target        39742 non-null  float64
 27  umpires_call       82504 non-null  object
 28  player_of_match    82504 non-null  object
 29  match_won_by       82504 non-null  object
 30  win_outcome        81396 non-null  object
 31  toss_winner        82504 non-null  object
 32  toss_decision      82504 non-null  object
 33  venue              82504 non-null  object
 34  city               82504 non-null  object
 35  day                82505 non-null  int64
 36  month              82505 non-null  int64
 37  year               82505 non-null  int64
 38  season             82504 non-null  object
 39  gender             82504 non-null  object
 40  team_type          82504 non-null  object
 41  superover_winner   1045 non-null   object
 42  result_type        1108 non-null   object
 43  method             1354 non-null   object
 44  balls_per_over     82504 non-null  float64
 45  overs              82504 non-null  float64
 46  event_match_no     82504 non-null  object
 47  stage              82504 non-null  object
 48  match_number       82504 non-null  object
 49  team_runs          82504 non-null  float64
 50  team_balls         82504 non-null  float64
 51  team_wicket        82504 non-null  float64
 52  new_batter         3969 non-null   object
 53  batter_runs        82504 non-null  float64
 54  batter_balls       82504 non-null  float64
 55  bowler_wicket      82504 non-null  float64
 56  batting_partners   82504 non-null  object
 57  next_batter        3970 non-null   object
 58  striker_out        82504 non-null  object
 59  ball_result        82505 non-null  object
dtypes: datetime64[ns](1), float64(16), int64(9), object(34)
memory usage: 37.8+ MB

In [26]:
# Display summary statistics
df.describe()

,match_id,date,innings,over,ball,ball_no,bat_pos,runs_batter,balls_faced,valid_ball,runs_extras,runs_total,runs_bowler,non_striker_pos,runs_target,day,month,year,balls_per_over,overs,team_runs,team_balls,team_wicket,batter_runs,batter_balls,bowler_wicket
count,82505.000000,82504,82505.000000,82505.000000,82505.000000,82505.000000,82505.000000,82504.000000,82504.000000,82504.000000,82504.000000,82504.000000,82504.000000,82504.000000,39742.000000,82505.000000,82505.000000,82505.000000,82504.0,82504.0,82504.000000,82504.000000,82504.000000,82504.000000,82504.000000,82504.000000
mean,459145.853851,2010-09-07 12:51:11.501987584,1.483013,9.134525,3.486286,9.134525,3.645561,1.188415,0.968971,0.964317,0.072166,1.260581,1.232098,3.638514,159.207589,15.648446,4.346076,2010.343567,6.0,20.0,71.453493,58.256715,2.471298,16.836905,13.904368,0.044507
min,0.000000,2008-04-18 00:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,52.000000,0.000000,0.000000,0.000000,6.0,20.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,392213.000000,2009-05-07 00:00:00,1.000000,4.000000,2.000000,4.000000,2.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,2.000000,140.000000,9.000000,4.000000,2009.000000,6.0,20.0,33.000000,29.000000,1.000000,4.000000,5.000000,0.000000
50%,419164.000000,2010-04-24 00:00:00,1.000000,9.000000,3.000000,9.000000,3.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,3.000000,161.000000,16.000000,4.000000,2010.000000,6.0,20.0,68.000000,58.000000,2.000000,11.000000,11.000000,0.000000
75%,548320.000000,2012-04-13 00:00:00,2.000000,14.000000,5.000000,14.000000,5.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,5.000000,179.000000,22.000000,5.000000,2012.000000,6.0,20.0,105.000000,87.000000,4.000000,24.000000,20.000000,0.000000
max,598048.000000,2013-04-20 00:00:00,4.000000,19.000000,7.000000,19.000000,11.000000,6.000000,1.000000,1.000000,5.000000,7.000000,7.000000,11.000000,247.000000,31.000000,6.000000,2013.000000,6.0,20.0,246.000000,121.000000,10.000000,158.000000,73.000000,1.000000
std,83745.556849,NaN,0.501796,5.670424,1.709138,5.670424,2.159381,1.568341,0.173397,0.185500,0.359696,1.558746,1.563327,2.153619,29.484502,8.114783,0.635189,7.169783,0.0,0.0,46.420877,34.059418,2.090872,17.460337,11.772777,0.206220

In [27]:
# Check missing values in each column
df.isnull().sum()

match_id                 0
date                     1
match_type               1
event_name               1
innings                  0
batting_team             1
bowling_team             1
over                     0
ball                     0
ball_no                  0
batter                   1
bat_pos                  0
runs_batter              1
balls_faced              1
bowler                   1
valid_ball               1
runs_extras              1
runs_total               1
runs_bowler              1
runs_not_boundary        1
extra_type           77842
non_striker              1
non_striker_pos          1
wicket_kind          78385
player_out           78385
fielders             79537
runs_target          42763
umpires_call             1
player_of_match          1
match_won_by             1
win_outcome           1109
toss_winner              1
toss_decision            1
venue                    1
city                     1
day                      0
month                    0
year                     0
season                   1
gender                   1
team_type                1
superover_winner     81460
result_type          81397
method               81151
balls_per_over           1
overs                    1
event_match_no           1
stage                    1
match_number             1
team_runs                1
team_balls               1
team_wicket              1
new_batter           78536
batter_runs              1
batter_balls             1
bowler_wicket            1
batting_partners         1
next_batter          78535
striker_out              1
ball_result              0
dtype: int64

In [32]:
# Remove columns that contain only missing values
# The previously listed columns were not found in the DataFrame, so they have been removed from the drop list.

print("Unnecessary columns removed successfully.")

Unnecessary columns removed successfully.

In [33]:
# Remove columns that contain only missing values
duplicate_count = df.duplicated().sum()

print("Duplicate Rows:", duplicate_count)

Duplicate Rows: 0

In [34]:
# Clean text columns
# Remove leading/trailing spaces
text_columns = df.select_dtypes(include='object').columns

for col in text_columns:

    df[col] = df[col].apply(lambda x: x.strip() if isinstance(x, str) else x)

print("Text columns cleaned successfully.")

Text columns cleaned successfully.

In [35]:
# Convert data types
df['date'] = pd.to_datetime(df['date'])
integer_columns = [
    'match_id',
    'innings',
    'over',
    'ball',
    'ball_no',
    'bat_pos',
    'day',
    'month',
    'year'
]

for col in integer_columns:
    df[col] = df[col].fillna(0).astype(int)

print("Data types updated successfully.")

Data types updated successfully.

In [36]:
# Standardize column names
df.columns = (df.columns
                .str.strip()
                .str.lower()
                .str.replace(" ", "_"))

print("Column names standardized successfully.")

Column names standardized successfully.

In [37]:
# Create a new column: ball_result
def ball_result(runs):
    if runs == 0:
        return "Dot Ball"
    elif runs == 1:
        return "Single"
    elif runs == 2:
        return "Double"
    elif runs == 3:
        return "Triple"
    elif runs == 4:
        return "Four"
    elif runs == 6:
        return "Six"
    else:
        return "Other"

df["ball_result"] = df["runs_batter"].apply(ball_result)

print("New column 'ball_result' created successfully.")

New column 'ball_result' created successfully.

In [38]:
# Display the first few rows of the new column
df[["runs_batter", "ball_result"]].head(10)

   runs_batter ball_result
0          0.0    Dot Ball
1          0.0    Dot Ball
2          0.0    Dot Ball
3          0.0    Dot Ball
4          0.0    Dot Ball
5          0.0    Dot Ball
6          0.0    Dot Ball
7          0.0    Dot Ball
8          4.0        Four
9          4.0        Four

In [39]:
# Final dataset information
print("Dataset Shape:", df.shape)
print("\nMissing Values:\n")
print(df.isnull().sum())

print("\nDataset Information:\n")
df.info()

Dataset Shape: (82505, 60)

Missing Values:

match_id                 0
date                     1
match_type               1
event_name               1
innings                  0
batting_team             1
bowling_team             1
over                     0
ball                     0
ball_no                  0
batter                   1
bat_pos                  0
runs_batter              1
balls_faced              1
bowler                   1
valid_ball               1
runs_extras              1
runs_total               1
runs_bowler              1
runs_not_boundary        1
extra_type           77842
non_striker              1
non_striker_pos          1
wicket_kind          78385
player_out           78385
fielders             79537
runs_target          42763
umpires_call             1
player_of_match          1
match_won_by             1
win_outcome           1109
toss_winner              1
toss_decision            1
venue                    1
city                     1
day                      0
month                    0
year                     0
season                   1
gender                   1
team_type                1
superover_winner     81460
result_type          81397
method               81151
balls_per_over           1
overs                    1
event_match_no           1
stage                    1
match_number             1
team_runs                1
team_balls               1
team_wicket              1
new_batter           78536
batter_runs              1
batter_balls             1
bowler_wicket            1
batting_partners         1
next_batter          78535
striker_out              1
ball_result              0
dtype: int64

Dataset Information:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82505 entries, 0 to 82504
Data columns (total 60 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   match_id           82505 non-null  int64
 1   date               82504 non-null  datetime64[ns]
 2   match_type         82504 non-null  object
 3   event_name         82504 non-null  object
 4   innings            82505 non-null  int64
 5   batting_team       82504 non-null  object
 6   bowling_team       82504 non-null  object
 7   over               82505 non-null  int64
 8   ball               82505 non-null  int64
 9   ball_no            82505 non-null  int64
 10  batter             82504 non-null  object
 11  bat_pos            82505 non-null  int64
 12  runs_batter        82504 non-null  float64
 13  balls_faced        82504 non-null  float64
 14  bowler             82504 non-null  object
 15  valid_ball         82504 non-null  float64
 16  runs_extras        82504 non-null  float64
 17  runs_total         82504 non-null  float64
 18  runs_bowler        82504 non-null  float64
 19  runs_not_boundary  82504 non-null  object
 20  extra_type         4663 non-null   object
 21  non_striker        82504 non-null  object
 22  non_striker_pos    82504 non-null  float64
 23  wicket_kind        4120 non-null   object
 24  player_out         4120 non-null   object
 25  fielders           2968 non-null   object
 26  runs_target        39742 non-null  float64
 27  umpires_call       82504 non-null  object
 28  player_of_match    82504 non-null  object
 29  match_won_by       82504 non-null  object
 30  win_outcome        81396 non-null  object
 31  toss_winner        82504 non-null  object
 32  toss_decision      82504 non-null  object
 33  venue              82504 non-null  object
 34  city               82504 non-null  object
 35  day                82505 non-null  int64
 36  month              82505 non-null  int64
 37  year               82505 non-null  int64
 38  season             82504 non-null  object
 39  gender             82504 non-null  object
 40  team_type          82504 non-null  object
 41  superover_winner   1045 non-null   object
 42  result_type        1108 non-null   object
 43  method             1354 non-null   object
 44  balls_per_over     82504 non-null  float64
 45  overs              82504 non-null  float64
 46  event_match_no     82504 non-null  object
 47  stage              82504 non-null  object
 48  match_number       82504 non-null  object
 49  team_runs          82504 non-null  float64
 50  team_balls         82504 non-null  float64
 51  team_wicket        82504 non-null  float64
 52  new_batter         3969 non-null   object
 53  batter_runs        82504 non-null  float64
 54  batter_balls       82504 non-null  float64
 55  bowler_wicket      82504 non-null  float64
 56  batting_partners   82504 non-null  object
 57  next_batter        3970 non-null   object
 58  striker_out        82504 non-null  object
 59  ball_result        82505 non-null  object
dtypes: datetime64[ns](1), float64(16), int64(9), object(34)
memory usage: 37.8+ MB

In [40]:
# Export cleaned dataset
df.to_csv("cleaned_dataset.csv", index=False)

print("Cleaned dataset exported successfully as 'cleaned_dataset.csv'")

Cleaned dataset exported successfully as 'cleaned_dataset.csv'